=== jabid021/Sopra-210413/Workspace/DemoXML/src/personnes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">





<!-- 
Elements Basiques / Simples :   attributs + balises PCDATA uniquement (PAS d'ATTRIBUTS : 

Balises : 
				nom, prenom, age,numero,voie


				Attributs : id, genre,type(tel),cp,type(mail)


___________________________________________

Elements Complexes : Le reste (balise qui contient des balises ou des attributs)

Balises : 
personnes8, personne7, adresse6, ville(1), tels5, tel2,mails4,mail3

 -->
 <xsd:simpleType name="typeUse">
 	<xsd:restriction base="xsd:string"> 
 		<xsd:enumeration value="pro"/>
 		<xsd:enumeration value="perso"/>
 	</xsd:restriction>
 </xsd:simpleType>
 
  <xsd:simpleType name="civ">
 	<xsd:restriction base="xsd:string"> 
 		<xsd:enumeration value="homme"/>
 		<xsd:enumeration value="femme"/>
 		<xsd:enumeration value="nb"/>
 	</xsd:restriction>
 </xsd:simpleType>
 
 
 <xsd:attribute name="id" type="xsd:ID"/>
 <xsd:attribute name="genre" type="civ"/>
 <xsd:attribute name="type" type="typeUse"/>
 <xsd:attribute name="cp" type="xsd:string"/>
 
 
 <xsd:element name="nom" type="xsd:string"/>
 <xsd:element name="prenom" type="xsd:string"/>
 <xsd:element name="age" type="xsd:positiveInteger"/>
 <xsd:element name="numero" type="xsd:string"/>
 <xsd:element name="voie" type="xsd:string"/>
 

	
 <xsd:element name="ville">
 	<xsd:complexType mixed="true">
 		<xsd:attribute ref="cp"/>
 	</xsd:complexType>
 	 </xsd:element>
 	
 	
 	<xsd:element name="tel">
 	<xsd:complexType mixed="true">
 		<xsd:attribute ref="type"/>
 	</xsd:complexType>
 </xsd:element>
 
 
  	<xsd:element name="mail">
 	<xsd:complexType mixed="true">
 		<xsd:attribute ref="type"/>
 	</xsd:complexType>
 </xsd:element>
 
 
 
  	<xsd:element name="tels">
 		<xsd:complexType>
 		<xsd:sequence>
 			<xsd:element ref="tel" maxOccurs="unbounded"/>
 		</xsd:sequence>
 		</xsd:complexType>
 </xsd:element>
 
 
 <xsd:element name="mails">
 		<xsd:complexType>
 		<xsd:sequence>
 			<xsd:element ref="mail" minOccurs="0" maxOccurs="unbounded"/>
 		</xsd:sequence>
 		</xsd:complexType>
 </xsd:element>
 
 
 <xsd:element name="adresse">
 		<xsd:complexType>
 		<xsd:all>
 			<xsd:element ref="numero" minOccurs="0"/>
 			<xsd:element ref="voie" minOccurs="0"/>
 			<xsd:element ref="ville" minOccurs="0"/>
 		</xsd:all>
 		</xsd:complexType>
 </xsd:element>
 
 
 
  <xsd:element name="personne">
 		<xsd:complexType mixed="true">
 		<xsd:sequence>
 			<xsd:element ref="nom"/>
 			<xsd:element ref="prenom"/>
 			<xsd:element ref="age"/>
 			<xsd:element ref="adresse"/>
 			<xsd:element ref="tels" minOccurs="0"/>
 			<xsd:element ref="mails"/>
 		</xsd:sequence>
 		<xsd:attribute ref="id"/>
 		<xsd:attribute ref="genre"/>
 		</xsd:complexType>
 </xsd:element>
 
 
 
 
 <xsd:element name="personnes">
 		<xsd:complexType>
 		<xsd:sequence>
 			<xsd:element ref="personne" maxOccurs="unbounded"/>
 		</xsd:sequence>
 		</xsd:complexType>
 </xsd:element>
 
 

</xsd:schema>

=== jabid021/Sopra-210413/Workspace/DemoXML/src/personnes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>


<!--  Personne : id*, nom*, prenom*, age*, genre*,

 adresse (rue,voie,cp,ville), tels (pro / perso) mails* (pro/perso) -->
 
<!-- Balise Racine -->

<!--<!DOCTYPE personnes SYSTEM  "personnes.dtd">-->








<personnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personnes.xsd">


<personne id="p12" genre="homme">
	<nom>Abid</nom>
	<prenom>Jordan</prenom>	
	<age>28</age>
	<adresse>
		<numero>6</numero>
		<voie>Rue rougemont</voie>
		<ville cp="75009">Paris</ville>
	</adresse>
	<tels>
		<tel type="pro">06789944788</tel>
		<tel type="perso">067114224</tel>
	</tels>
	<mails>
		<mail type="perso">jordanabid@gmail.com</mail>
		<mail type="pro">j.abid@ajc-ingenierie.fr</mail>
	</mails>
</personne>



<personne  genre="homme" id="p14">
	<nom>Abid</nom>
	<prenom>Jordan</prenom>	
	<age>28</age>
	<adresse>
		<numero>6</numero>
		<voie>Rue rougemont</voie>
		<ville cp="75009">Paris</ville>
	</adresse>
	<mails/>
</personne>

<personne id = "p34" genre="femme">
<nom>Florentin</nom>
<prenom>Axelle</prenom>
<age>27</age>
<adresse>
    <numero>47</numero>
    <voie>rue de la boulais</voie>
    <ville cp="35000">Rennes</ville>
</adresse>

<mails>
    <mail type="pro">florentin.axelle@gmail.com</mail>
</mails>
</personne>




</personnes>
